name: Update Workshop

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: steam-workshop-update
      uses: actions/checkout@latest
      uses: hmlendea/steam-workshop-update@v1.2.0
      with:
        appid: 294100 # The game's Steam App ID
        itemid: 3531401512 # The mod's Steam Workshop Item ID
        path: 'Mod' # Relative path to your mod's folder, starting from the repository root
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }} # The Steam account username
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }} # The Steam account password
        STEAM_2FASEED: ${{ secrets.STEAM_2FASEED }} # The Steam account 2FA seed (standard TOTP, not the SteamGuard base64 secret)
